### ISSUE TITLE
"Unable to parse configuration file" in 0.63.33

### ISSUE THREAD

**Issue by ABelliqueux** [tboegi/GpsMaster#3]
Hi,
In 0.63.33, the following message appears on startup :
> Unable to parse configuration file, using defaults. existing file will be overwritten on exit.

It prevents the addition of "onlineTileSources" in GpsMaster.config.

**Comment by rfuegen** [comment]
hi,  this bug should be fixed in version 0.63.34. 

compiled jar is available here: http://www.gpsmaster.org/download/

**Comment by RealVegOs** [comment]
Alas-Omaiomai! It is not! I still have this issue on Debian and Devuan too, each the latest version. Please fix it. The configuration file in $HOME is overwritten on exit with zero content, even if you created the file manually. BTW I do not like Java but I like the program after I experienced Viking to be quite stupid.

**Comment by tboegi** [comment]
Could you guys test to start GpsMaster like this:
java --add-modules java.xml.bind -jar  GpsMaster_0.63.34.JDK7-13.jar

https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by RealVegOs** [comment]
I got this: ~$ java --add-modules java.xml.bind -jar GpsMaster/GpsMaster.jar 
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found

I googled a bit:
See here: https://www.oracle.com/technetwork/java/javase/11-relnote-issues-5012449.html#JDK-8190378

Found this hint here:
https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist

Don't know whether it helps you, I'm no dev. Cheers

**Comment by tboegi** [comment]
Thanks for testing - 
Which java version do you use ?
(I wish that I had all versions in house, but I haven't.
 So I would need your help here)

**Comment by Rakambda** [comment]
I got the same error with
```
$ java --version
openjdk 14.0.1 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
```

**Comment by RealVegOs** [comment]
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1deb10u1, mixed mode, sharing)

If fixed, would GpsMaster also save it's last status (opened tracks etc.)?

**Comment by rfuegen** [comment]
as of now, GpsMaster saves on exit:
- last map position (lat, lon)
- map zoom level
- last file open / file save directories
it does not remember the tracks last opened.

hth.

**Comment by tboegi** [comment]
Folks,
I uploaded 2 jar.gz files.
If you have Java 11,
please download the GpsMaster_0.63.35.JDK11-and-higher.jar.gz file, unpack and test.

Java 7/8 users should use the GpsMaster_0.63.35.JDK7-8.jar.gz file.
Java 9/10 users could use GpsMaster_0.63.35.JDK7-8.jar.gz as well, they have to
live with the config file problem (or install a later Java version, sorry guys)

**Comment by Rakambda** [comment]
Solves the problem for me (JDK 14)

**Comment by RealVegOs** [comment]
Where to download? I cant find it on http://www.gpsmaster.org/download/.

**Comment by Rakambda** [comment]
On the releases page (https://github.com/tboegi/GpsMaster/releases/tag/v0.63.35-rc0)

**Comment by tboegi** [comment]
Thanks for testing.
@rfuegen : Could you download the jar to the official page?

**Comment by RealVegOs** [comment]
THX wagons full of much!

**Comment by RealVegOs** [comment]
Works for me too. Thanks again.

**Comment by rfuegen** [comment]
upload to http://www.gpsmaster.org/download/ done.

**Comment by tboegi** [comment]
http://www.gpsmaster.org/download/
